Repository OCA/account-financial-reporting, pull requests merged in 2018-11, with the labels that each got.

#416 [ADD][10.0] account_financial_report_qweb: add analytic tags
  account_financial_report_qweb/report/general_ledger.py
  account_financial_report_qweb/report/general_ledger_xlsx.py
  account_financial_report_qweb/report/templates/general_ledger.xml
  account_financial_report_qweb/tests/test_general_ledger.py
  account_financial_report_qweb/wizard/general_ledger_wizard.py
  account_financial_report_qweb/wizard/general_ledger_wizard_view.xml
Labels: approved, needs review, ready to merge

#479 [11.0][MIG] account_financial_report_date_range
  account_financial_report_date_range/README.rst
  account_financial_report_date_range/__init__.py
  account_financial_report_date_range/__manifest__.py
  account_financial_report_date_range/i18n/account_financial_report_date_range.pot
  account_financial_report_date_range/readme/CONTRIBUTORS.rst
  account_financial_report_date_range/readme/DESCRIPTION.rst
  account_financial_report_date_range/readme/INSTALL.rst
  account_financial_report_date_range/static/description/icon.png
  account_financial_report_date_range/tests/__init__.py
  account_financial_report_date_range/tests/test_accounting_report.py
  account_financial_report_date_range/wizards/__init__.py
  account_financial_report_date_range/wizards/account_common_report.py
  account_financial_report_date_range/wizards/accounting_report.xml
Labels: approved, needs review

#481 [11][account_financial_report] trial balance: remove account groups if hierarchy = 'none'
  account_financial_report/report/trial_balance.py
Labels: approved

#484 [11.0][account_financial_report][IMP] Refactoring
  account_financial_report/README.rst
  account_financial_report/__manifest__.py
  account_financial_report/readme/CONTRIBUTORS.rst
  account_financial_report/readme/DESCRIPTION.rst
  account_financial_report/readme/HISTORY.rst
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/general_ledger.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/open_items.py
  account_financial_report/report/open_items_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/report/templates/open_items.xml
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/trial_balance.py
  account_financial_report/report/trial_balance_xlsx.py
  account_financial_report/static/description/index.html
  account_financial_report/tests/test_general_ledger.py
  account_financial_report/tests/test_open_items.py
  account_financial_report/tests/test_trial_balance.py
  account_financial_report/wizard/aged_partner_balance_wizard.py
  account_financial_report/wizard/aged_partner_balance_wizard_view.xml
  account_financial_report/wizard/general_ledger_wizard.py
  account_financial_report/wizard/general_ledger_wizard_view.xml
  account_financial_report/wizard/journal_ledger_wizard.py
  account_financial_report/wizard/open_items_wizard.py
  account_financial_report/wizard/open_items_wizard_view.xml
  account_financial_report/wizard/trial_balance_wizard.py
  account_financial_report/wizard/trial_balance_wizard_view.xml
Labels: needs review

#485 [10.0][account_financial_report_qweb] backport latest changes from 11.0
  account_financial_report_qweb/README.rst
  account_financial_report_qweb/__manifest__.py
  account_financial_report_qweb/models/account_group.py
  account_financial_report_qweb/readme/CONTRIBUTORS.rst
  account_financial_report_qweb/readme/DESCRIPTION.rst
  account_financial_report_qweb/readme/HISTORY.rst
  account_financial_report_qweb/report/abstract_report_xlsx.py
  account_financial_report_qweb/report/general_ledger.py
  account_financial_report_qweb/report/general_ledger_xlsx.py
  account_financial_report_qweb/report/open_items.py
  account_financial_report_qweb/report/open_items_xlsx.py
  account_financial_report_qweb/report/templates/general_ledger.xml
  account_financial_report_qweb/report/templates/open_items.xml
  account_financial_report_qweb/report/templates/trial_balance.xml
  account_financial_report_qweb/report/trial_balance.py
  account_financial_report_qweb/report/trial_balance_xlsx.py
  account_financial_report_qweb/static/description/index.html
  account_financial_report_qweb/tests/test_general_ledger.py
  account_financial_report_qweb/tests/test_open_items.py
  account_financial_report_qweb/tests/test_trial_balance.py
  account_financial_report_qweb/wizard/aged_partner_balance_wizard.py
  account_financial_report_qweb/wizard/aged_partner_balance_wizard_view.xml
  account_financial_report_qweb/wizard/general_ledger_wizard.py
  account_financial_report_qweb/wizard/general_ledger_wizard_view.xml
  account_financial_report_qweb/wizard/journal_report_wizard.py
  account_financial_report_qweb/wizard/open_items_wizard.py
  account_financial_report_qweb/wizard/open_items_wizard_view.xml
  account_financial_report_qweb/wizard/trial_balance_wizard.py
  account_financial_report_qweb/wizard/trial_balance_wizard_view.xml
Labels: needs review
