Repository OCA/account-financial-reporting, pull requests merged in 2019-04, with the labels that each got.

#476 [8.0] [FIX] account_financial_report_webkit: overlapping headers
  account_financial_report_webkit/report/templates/account_report_general_ledger.mako
  account_financial_report_webkit/report/templates/aged_trial_webkit.mako
Labels: needs review

#458 Format Improvements for customer outstanding statement
  customer_outstanding_statement/__manifest__.py
  customer_outstanding_statement/static/src/less/layout_statement.less
  customer_outstanding_statement/views/statement.xml
Labels: approved

#517 [11.0][customer_outstanding_statement] minor fixes
  customer_outstanding_statement/__manifest__.py
  customer_outstanding_statement/report/customer_outstanding_statement.py
  customer_outstanding_statement/views/statement.xml
Labels: approved, ready to merge

#541 [11.0] account_financial_report: add option to hide parent hierarchy levels
  account_financial_report/README.rst
  account_financial_report/__manifest__.py
  account_financial_report/readme/HISTORY.rst
  account_financial_report/report/trial_balance.py
  account_financial_report/wizard/trial_balance_wizard.py
  account_financial_report/wizard/trial_balance_wizard_view.xml
Labels: approved

#540 [10.0] account_financial_report_qweb: add option to hide parent hierarchy levels
  account_financial_report_qweb/README.rst
  account_financial_report_qweb/__manifest__.py
  account_financial_report_qweb/readme/HISTORY.rst
  account_financial_report_qweb/report/trial_balance.py
  account_financial_report_qweb/wizard/trial_balance_wizard.py
  account_financial_report_qweb/wizard/trial_balance_wizard_view.xml
Labels: approved
