Repository OCA/account-financial-reporting, pull requests merged in 2019-01, with the labels that each got.

#489 11.0 imp account financial report multicompany 2
  account_financial_report/README.rst
  account_financial_report/__manifest__.py
  account_financial_report/readme/CONTRIBUTORS.rst
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/aged_partner_balance_xlsx.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/journal_ledger_xlsx.py
  account_financial_report/report/open_items_xlsx.py
  account_financial_report/report/templates/aged_partner_balance.xml
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/report/templates/journal_ledger.xml
  account_financial_report/report/templates/layouts.xml
  account_financial_report/report/templates/open_items.xml
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/templates/vat_report.xml
  account_financial_report/report/trial_balance_xlsx.py
  account_financial_report/report/vat_report_xlsx.py
  account_financial_report/tests/test_vat_report.py
  account_financial_report/wizard/aged_partner_balance_wizard.py
  account_financial_report/wizard/aged_partner_balance_wizard_view.xml
  account_financial_report/wizard/general_ledger_wizard.py
  account_financial_report/wizard/general_ledger_wizard_view.xml
  account_financial_report/wizard/open_items_wizard.py
  account_financial_report/wizard/open_items_wizard_view.xml
  account_financial_report/wizard/trial_balance_wizard.py
  account_financial_report/wizard/trial_balance_wizard_view.xml
  account_financial_report/wizard/vat_report_wizard.py
Labels: approved, needs review

#498 [11.0][account_financial_report] Fix wizards for proper multicompany behaviour
  account_financial_report/__manifest__.py
  account_financial_report/readme/HISTORY.rst
  account_financial_report/report/general_ledger.py
  account_financial_report/report/templates/aged_partner_balance.xml
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/report/templates/journal_ledger.xml
  account_financial_report/report/templates/open_items.xml
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/templates/vat_report.xml
  account_financial_report/wizard/aged_partner_balance_wizard.py
  account_financial_report/wizard/aged_partner_balance_wizard_view.xml
  account_financial_report/wizard/general_ledger_wizard.py
  account_financial_report/wizard/general_ledger_wizard_view.xml
  account_financial_report/wizard/journal_ledger_wizard.py
  account_financial_report/wizard/open_items_wizard.py
  account_financial_report/wizard/open_items_wizard_view.xml
  account_financial_report/wizard/trial_balance_wizard.py
  account_financial_report/wizard/trial_balance_wizard_view.xml
  account_financial_report/wizard/vat_report_wizard.py
  account_financial_report/wizard/vat_report_wizard_view.xml
Labels: approved

#497 [10.0][ADD] account_financial_report_web: add index on account_move_line to speed up report rendering
  account_financial_report_qweb/__manifest__.py
  account_financial_report_qweb/models/__init__.py
  account_financial_report_qweb/models/account_move_line.py
Labels: approved

#490 [10.0][IMP] account_financial_report: adapt the wizards to multicompany
  account_financial_report_qweb/README.rst
  account_financial_report_qweb/__manifest__.py
  account_financial_report_qweb/readme/CONTRIBUTORS.rst
  account_financial_report_qweb/readme/HISTORY.rst
  account_financial_report_qweb/report/abstract_report_xlsx.py
  account_financial_report_qweb/report/aged_partner_balance_xlsx.py
  account_financial_report_qweb/report/general_ledger_xlsx.py
  account_financial_report_qweb/report/journal_report_xlsx.py
  account_financial_report_qweb/report/open_items_xlsx.py
  account_financial_report_qweb/report/templates/aged_partner_balance.xml
  account_financial_report_qweb/report/templates/general_ledger.xml
  account_financial_report_qweb/report/templates/journal.xml
  account_financial_report_qweb/report/templates/layouts.xml
  account_financial_report_qweb/report/templates/open_items.xml
  account_financial_report_qweb/report/templates/trial_balance.xml
  account_financial_report_qweb/report/trial_balance_xlsx.py
  account_financial_report_qweb/wizard/aged_partner_balance_wizard.py
  account_financial_report_qweb/wizard/aged_partner_balance_wizard_view.xml
  account_financial_report_qweb/wizard/general_ledger_wizard.py
  account_financial_report_qweb/wizard/general_ledger_wizard_view.xml
  account_financial_report_qweb/wizard/journal_report_wizard.py
  account_financial_report_qweb/wizard/open_items_wizard.py
  account_financial_report_qweb/wizard/open_items_wizard_view.xml
  account_financial_report_qweb/wizard/trial_balance_wizard.py
  account_financial_report_qweb/wizard/trial_balance_wizard_view.xml
Labels: approved, needs review

#503 [10.0][FIX] account_financial_report_qweb: Link reconcile model instead just name
  account_financial_report_qweb/report/abstract_report.py
  account_financial_report_qweb/report/general_ledger.py
  account_financial_report_qweb/report/general_ledger_xlsx.py
  account_financial_report_qweb/report/open_items.py
  account_financial_report_qweb/report/templates/general_ledger.xml
  account_financial_report_qweb/report/templates/open_items.xml
  account_financial_report_qweb/static/src/js/account_financial_report_qweb_backend.js
  account_financial_report_qweb/static/src/js/account_financial_report_qweb_widgets.js
  customer_activity_statement/report/customer_activity_statement.py
Labels: approved, ready to merge

#502 [10.0][IMP] account_financial_report_qweb : filter for partner
  account_financial_report_qweb/wizard/aged_partner_balance_wizard.py
  account_financial_report_qweb/wizard/general_ledger_wizard.py
  account_financial_report_qweb/wizard/open_items_wizard.py
  account_financial_report_qweb/wizard/trial_balance_wizard.py
Labels: approved, ready to merge

#508 [10.0][IMP] Add report to res partner, default values
  account_financial_report_qweb/static/src/js/account_financial_report_qweb_widgets.js
  account_financial_report_qweb/tests/test_general_ledger.py
  account_financial_report_qweb/tests/test_open_items.py
  account_financial_report_qweb/wizard/general_ledger_wizard.py
  account_financial_report_qweb/wizard/general_ledger_wizard_view.xml
  account_financial_report_qweb/wizard/open_items_wizard.py
  account_financial_report_qweb/wizard/open_items_wizard_view.xml
Labels: approved, ready to merge
