Repository OCA/account-financial-reporting, pull requests merged in 2020-04, with the labels that each got.

#673 [FIX] account_financial_report: Fix error when generating reports
  account_financial_report/report/general_ledger.py
  account_financial_report/report/journal_ledger.py
  account_financial_report/report/trial_balance.py
Labels: approved, bot is merging ⏳

#670 [13.0][FIX] account_financial_report: general_ledger
  account_financial_report/report/general_ledger.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/report/trial_balance_xlsx.py
Labels: approved, bot is merging ⏳

#674 [13.0][FIX] account_financial_report: open_items
  account_financial_report/report/open_items.py
Labels: bot is merging ⏳

#654 [13.0][MIG] partner_statement
  partner_statement/README.rst
  partner_statement/__init__.py
  partner_statement/__manifest__.py
  partner_statement/i18n/ca.po
  partner_statement/i18n/de.po
  partner_statement/i18n/es.po
  partner_statement/i18n/fr.po
  partner_statement/i18n/hr_HR.po
  partner_statement/i18n/it.po
  partner_statement/i18n/nl.po
  partner_statement/i18n/nl_NL.po
  partner_statement/i18n/partner_statement.pot
  partner_statement/i18n/pt.po
  partner_statement/i18n/pt_BR.po
  partner_statement/i18n/ro.po
  partner_statement/readme/CONFIGURE.rst
  partner_statement/readme/CONTRIBUTORS.rst
  partner_statement/readme/DESCRIPTION.rst
  partner_statement/readme/HISTORY.rst
  partner_statement/readme/ROADMAP.rst
  partner_statement/readme/USAGE.rst
  partner_statement/report/__init__.py
  partner_statement/report/activity_statement.py
  partner_statement/report/outstanding_statement.py
  partner_statement/report/report_statement_common.py
  partner_statement/security/statement_security.xml
  partner_statement/static/description/icon.png
  partner_statement/static/description/index.html
  partner_statement/static/src/scss/layout_statement.scss
  partner_statement/tests/__init__.py
  partner_statement/tests/test_activity_statement.py
  partner_statement/tests/test_outstanding_statement.py
  partner_statement/tests/test_res_config_settings.py
  partner_statement/views/activity_statement.xml
  partner_statement/views/aging_buckets.xml
  partner_statement/views/assets.xml
  partner_statement/views/outstanding_statement.xml
  partner_statement/views/res_config_settings.xml
  partner_statement/wizard/__init__.py
  partner_statement/wizard/activity_statement_wizard.py
  partner_statement/wizard/outstanding_statement_wizard.py
  partner_statement/wizard/res_config_settings.py
  partner_statement/wizard/statement_common.py
  partner_statement/wizard/statement_wizard.xml
Labels: approved, bot is merging ⏳, ready to merge

#599 [12.0][ADD] partner_statement: migration scripts to v12
  partner_statement/migrations/12.0.1.0.0/pre-migration.py
Labels: approved, bot is merging ⏳, ready to merge
