Repository OCA/account-financial-reporting, pull requests merged in 2021-09, with the labels that each got.

#816 [14.0][FIX] account_financial_reporting: wrong view_id
  account_financial_report/wizard/open_items_wizard_view.xml
Labels: approved, bot is merging ⏳

#818 [14.0][FIX] account_financial_report: Filter column creation to have correct offset in Journal Ledger
  account_financial_report/report/templates/journal_ledger.xml
Labels: bot is merging ⏳

#811 [13.0][FIX] account_financial_report: Print report with details
  account_financial_report/report/aged_partner_balance.py
  account_financial_report/report/templates/aged_partner_balance.xml
  account_financial_report/tests/__init__.py
  account_financial_report/tests/test_aged_partner_balance.py
Labels: approved, ready to merge, bot is merging ⏳
