Repository OCA/account-financial-reporting, pull requests merged in 2021-06, with the labels that each got.

#796 [13.0][account_financial_report][fix] display correct target_move in Trial Balance XLSX
  account_financial_report/report/trial_balance_xlsx.py
Labels: approved, bot is merging ⏳

#797 [account_financial_report][fix] display correct target_move in Trial Balance XLSX
  account_financial_report/report/trial_balance_xlsx.py
Labels: bot is merging ⏳

#787 [13.0][IMP] account_financial_report: added 'auto sequence' option in Journal Ledger.
  account_financial_report/readme/CONTRIBUTORS.rst
  account_financial_report/report/journal_ledger.py
  account_financial_report/report/journal_ledger_xlsx.py
  account_financial_report/report/templates/journal_ledger.xml
  account_financial_report/wizard/journal_ledger_wizard.py
  account_financial_report/wizard/journal_ledger_wizard_view.xml
Labels: approved, bot is merging ⏳

#798 [14.0][IMP] account_financial_report: added 'auto sequence' option in Journal Ledger
  account_financial_report/readme/CONTRIBUTORS.rst
  account_financial_report/report/journal_ledger.py
  account_financial_report/report/journal_ledger_xlsx.py
  account_financial_report/report/templates/journal_ledger.xml
  account_financial_report/wizard/journal_ledger_wizard.py
  account_financial_report/wizard/journal_ledger_wizard_view.xml
Labels: approved, bot is merging ⏳

#799 [13.0][FIX] partner_statement: consider a multicurrency case
  partner_statement/report/activity_statement.py
  partner_statement/report/outstanding_statement.py
  partner_statement/report/report_statement_common.py
Labels: approved, bot is merging ⏳, ready to merge
