Repository OCA/account-financial-reporting, pull requests merged in 2021-01, with the labels that each got.

#748 [13.0][FIX] Journal ledger wizard to inherit from abstract report wizard
  account_financial_report/wizard/journal_ledger_wizard.py
Labels: approved, bot is merging ⏳

#732 [10.0][FIX] account_tax_balance: Empty bills/invoices should not be considered as refunds
  account_tax_balance/models/account_move.py
  account_tax_balance/tests/test_account_tax_balance.py
Labels: approved, bot is merging ⏳, ready to merge

#750 [12.0][FIX] account_financial_report: add index to report_move_id
  account_financial_report/report/journal_ledger.py
Labels: bot is merging ⏳
