Repository OCA/account-financial-reporting, pull requests merged in 2021-04, with the labels that each got.

#764 [14.0][FW-PORT][FIX] account_financial_report: Actions
  account_financial_report/README.rst
  account_financial_report/__manifest__.py
  account_financial_report/readme/CONTRIBUTORS.rst
  account_financial_report/report/templates/aged_partner_balance.xml
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/report/templates/journal_ledger.xml
  account_financial_report/report/templates/layouts.xml
  account_financial_report/report/templates/open_items.xml
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/templates/vat_report.xml
  account_financial_report/static/description/index.html
  account_financial_report/static/src/css/report.css
  account_financial_report/static/src/js/account_financial_report_backend.js
  account_financial_report/static/src/js/account_financial_report_widgets.js
  account_financial_report/static/src/js/action_manager_report.js
  account_financial_report/static/src/js/client_action.js
  account_financial_report/static/src/js/report.js
  account_financial_report/static/src/xml/report.xml
  account_financial_report/view/report_template.xml
Labels: bot is merging ⏳

#766 [14.0][FIX] account_financial_report fix default company
  account_financial_report/wizard/aged_partner_balance_wizard.py
  account_financial_report/wizard/general_ledger_wizard.py
  account_financial_report/wizard/journal_ledger_wizard.py
  account_financial_report/wizard/open_items_wizard.py
  account_financial_report/wizard/trial_balance_wizard.py
  account_financial_report/wizard/vat_report_wizard.py
Labels: bot is merging ⏳

#671 [12.0][FIX] Add missing date formatting to the VAT report
  account_financial_report/report/templates/vat_report.xml
Labels: approved, bot is merging ⏳, ready to merge

#677 [10.0] FIX account_financial_report_qweb trial balance: consider journals set in wizard
  account_financial_report_qweb/report/general_ledger.py
Labels: approved, bot is merging ⏳

#742 [FIX] account_financial_report: get module compatible with HomeMenu widget added by web_enterprise module
  account_financial_report/static/src/js/account_financial_report_backend.js
Labels: bot is merging ⏳

#773 [13.0][FIX]account_financial_report: fix VAT report template
  account_financial_report/report/templates/vat_report.xml
Labels: approved, bot is merging ⏳

#775 [13.0][FIX] account_financial_reporting: Pass res_id correctly to lines
  account_financial_report/report/open_items.py
  account_financial_report/report/templates/open_items.xml
Labels: approved, bot is merging ⏳

#776 [13.0][FIX] account_financial_report: allow navigation on all fields
  account_financial_report/report/templates/open_items.xml
Labels: approved, bot is merging ⏳

#777 [14.0][FIX] account_financial_report: allow navigation on all fields
  account_financial_report/report/open_items.py
  account_financial_report/report/templates/open_items.xml
  account_financial_report/tests/test_journal_ledger.py
  account_financial_report/wizard/open_items_wizard_view.xml
Labels: approved, bot is merging ⏳

#774 [14.0][FIX] account_financial_report: fix VAT report template
  account_financial_report/report/templates/vat_report.xml
  account_financial_report/tests/test_journal_ledger.py
Labels: approved, bot is merging ⏳, ready to merge

#778 [13.0][fix][partner_statement] correct default company
  partner_statement/wizard/statement_common.py
Labels: approved, bot is merging ⏳
