Repository OCA/account-financial-reporting, pull requests merged in 2021-05, with the labels that each got.

#781 [13.0][FIX] account_financial_report: Fix tests
  account_financial_report/tests/test_trial_balance.py
Labels: approved, bot is merging ⏳

#782 [14.0][FIX] account_financial_report: filter by correct data in trial balance
  account_financial_report/report/templates/trial_balance.xml
Labels: approved, bot is merging ⏳

#783 [14.0][FIX] account_tax_balance: Remove unnecessary text from button
  account_tax_balance/views/account_tax_view.xml
Labels: approved, bot is merging ⏳

#780 [14.0][FIX] account_financial_report: Don't include unaffected account if accounts are filtered
  account_financial_report/report/general_ledger.py
  account_financial_report/report/trial_balance.py
  account_financial_report/tests/test_general_ledger.py
  account_financial_report/tests/test_trial_balance.py
Labels: approved, bot is merging ⏳, ready to merge

#788 [FIX] account_financial_report: filter by correct data in trial balance
  account_financial_report/report/templates/trial_balance.xml
Labels: bot is merging ⏳

#791 [13.0][account_financial_report][fix] define XLSX currency format based on the currency of the company selected for the report.
  account_financial_report/report/abstract_report_xlsx.py
Labels: approved, bot is merging ⏳

#771 Manage renamed move_type column
  account_tax_balance/migrations/14.0.1.0.0/pre-migration.py
Labels: approved, bot is merging ⏳, ready to merge
