Repository OCA/account-financial-reporting, pull requests merged in 2022-09, with the labels that each got.

#899 [13.0] [FIX] mis_template_financial_report: Remove balance of "Current Year Earnings" in Profit.
  mis_template_financial_report/data/mis_report_kpi.xml
Labels: approved, bot is merging ⏳

#901 [14.0][FIX] mis_template_financial_report: Remove balance of "Current Year Earnings" in Profit.
  mis_template_financial_report/data/mis_report_kpi.xml
Labels: bot is merging ⏳

#902 [14.0][DCK] Updated from template
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  mis_builder_cash_flow/__manifest__.py
Labels: bot is merging ⏳

#898 [13.0][IMP] account_financial_report: Amount currency columns from general ledger.
  account_financial_report/README.rst
  account_financial_report/i18n/account_financial_report.pot
  account_financial_report/i18n/es.po
  account_financial_report/readme/CONTRIBUTORS.rst
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/general_ledger.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/static/description/index.html
Labels: approved, bot is merging ⏳

#885 [FIX] account_financial_report: Hide zero accounts also for partner details
  account_financial_report/report/templates/trial_balance.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#906 [13.0][FIX] account_financial_report: Add sorting to move line records in journal ledger.
  account_financial_report/report/journal_ledger.py
Labels: approved, bot is merging ⏳

#903 account_tax_balance: change development_status to Production/Stable
  account_tax_balance/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#910 [14.0][IMP] account_financial_report: Amount currency columns from general ledger.
  account_financial_report/README.rst
  account_financial_report/i18n/account_financial_report.pot
  account_financial_report/i18n/es.po
  account_financial_report/readme/CONTRIBUTORS.rst
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/general_ledger.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/static/description/index.html
Labels: approved, bot is merging ⏳

#913 [15.0][IMP] account_financial_report: Amount currency columns from general ledger.
  account_financial_report/README.rst
  account_financial_report/i18n/account_financial_report.pot
  account_financial_report/i18n/es.po
  account_financial_report/readme/CONTRIBUTORS.rst
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/general_ledger.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/static/description/index.html
Labels: approved, bot is merging ⏳

#916 [15.0][FIX] account_financial_report: Add sorting to move line records in journal ledger.
  account_financial_report/report/journal_ledger.py
Labels: approved, bot is merging ⏳

#917 [14.0][IMP] account_financial_report: Add tax detail to the general ledger report
  account_financial_report/i18n/account_financial_report.pot
  account_financial_report/i18n/es.po
  account_financial_report/report/general_ledger.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/tests/test_general_ledger.py
  account_financial_report/wizard/general_ledger_wizard.py
  account_financial_report/wizard/general_ledger_wizard_view.xml
Labels: approved, bot is merging ⏳

#919 [14.0][FIX] account_financial_report: Display the correct name of initial balance and ending balance in general ledger
  account_financial_report/i18n/account_financial_report.pot
  account_financial_report/i18n/es.po
  account_financial_report/report/templates/general_ledger.xml
Labels: bot is merging ⏳

#920 [13.0][FIX] account_financial_report: Display the correct name of initial balance and ending balance in general ledger
  account_financial_report/i18n/account_financial_report.pot
  account_financial_report/i18n/es.po
  account_financial_report/report/templates/general_ledger.xml
Labels: bot is merging ⏳

#922 [14.0][FIX] account_financial_report: variable not defined
  account_financial_report/report/general_ledger_xlsx.py
Labels: bot is merging ⏳

#923 [13.0][FIX] account_financial_report: Update the correct data.
  account_financial_report/report/general_ledger_xlsx.py
Labels: bot is merging ⏳
