Repository OCA/account-financial-reporting, pull requests merged in 2022-04, with the labels that each got.

#699 [13.0][MIG] account_bank_reconciliation_summary_xlsx
  account_bank_reconciliation_summary_xlsx/README.rst
  account_bank_reconciliation_summary_xlsx/__init__.py
  account_bank_reconciliation_summary_xlsx/__manifest__.py
  account_bank_reconciliation_summary_xlsx/i18n/fr.po
  account_bank_reconciliation_summary_xlsx/models/__init__.py
  account_bank_reconciliation_summary_xlsx/models/account_move_line.py
  account_bank_reconciliation_summary_xlsx/readme/CONFIGURE.rst
  account_bank_reconciliation_summary_xlsx/readme/CONTRIBUTORS.rst
  account_bank_reconciliation_summary_xlsx/readme/DESCRIPTION.rst
  account_bank_reconciliation_summary_xlsx/readme/USAGE.rst
  account_bank_reconciliation_summary_xlsx/report/__init__.py
  account_bank_reconciliation_summary_xlsx/report/bank_reconciliation_xlsx.py
  account_bank_reconciliation_summary_xlsx/report/report.xml
  account_bank_reconciliation_summary_xlsx/views/account_bank_statement.xml
  account_bank_reconciliation_summary_xlsx/views/account_journal.xml
  account_bank_reconciliation_summary_xlsx/views/account_move_line.xml
  account_bank_reconciliation_summary_xlsx/wizard/__init__.py
  account_bank_reconciliation_summary_xlsx/wizard/bank_reconciliation_report_wizard.py
  account_bank_reconciliation_summary_xlsx/wizard/bank_reconciliation_report_wizard_view.xml
  setup/account_bank_reconciliation_summary_xlsx/odoo/addons/account_bank_reconciliation_summary_xlsx
  setup/account_bank_reconciliation_summary_xlsx/setup.py
Labels: needs review, approved, bot is merging ⏳

#850 [14.0][FIX] account_financial_report: domain detail move line on target move
  account_financial_report/readme/CONTRIBUTORS.rst
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/static/src/js/report.js
Labels: needs review, approved, ready to merge, bot is merging ⏳

#874 [14.0][FIX] account_financial_report + account_tax_balance: Add post_install tag in tests to prevent test errors
  account_financial_report/tests/test_general_ledger.py
  account_financial_report/tests/test_journal_ledger.py
  account_financial_report/tests/test_open_items.py
  account_financial_report/tests/test_trial_balance.py
  account_financial_report/tests/test_vat_report.py
  account_tax_balance/tests/test_account_tax_balance.py
Labels: bot is merging ⏳
