Repository OCA/account-financial-reporting, pull requests merged in 2022-11, with the labels that each got.

#941 [15.0][FIX] pre-commit: update to v1.11.0
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#936 [15.0][FIX] partner_statement: avoid showing lines with 0.00001 open amounts (forwardport)
  partner_statement/report/outstanding_statement.py
  partner_statement/report/report_statement_common.py
Labels: bot is merging ⏳

#937 [16.0][MIG] account_tax_balance: Migration to 16.0
  account_tax_balance/README.rst
  account_tax_balance/__init__.py
  account_tax_balance/__manifest__.py
  account_tax_balance/hooks.py
  account_tax_balance/i18n/account_tax_balance.pot
  account_tax_balance/i18n/ca.po
  account_tax_balance/i18n/de.po
  account_tax_balance/i18n/es.po
  account_tax_balance/i18n/es_AR.po
  account_tax_balance/i18n/fr.po
  account_tax_balance/i18n/fr_FR.po
  account_tax_balance/i18n/hr_HR.po
  account_tax_balance/i18n/it.po
  account_tax_balance/i18n/nl.po
  account_tax_balance/i18n/nl_NL.po
  account_tax_balance/i18n/pt.po
  account_tax_balance/i18n/ro.po
  account_tax_balance/models/__init__.py
  account_tax_balance/models/account_move.py
  account_tax_balance/models/account_move_line.py
  account_tax_balance/models/account_tax.py
  account_tax_balance/readme/CONTRIBUTORS.rst
  account_tax_balance/readme/DESCRIPTION.rst
  account_tax_balance/readme/USAGE.rst
  account_tax_balance/security/ir.model.access.csv
  account_tax_balance/static/description/icon.png
  account_tax_balance/static/description/index.html
  account_tax_balance/static/description/tax_balance.png
  account_tax_balance/tests/__init__.py
  account_tax_balance/tests/test_account_tax_balance.py
  account_tax_balance/views/account_move_view.xml
  account_tax_balance/views/account_tax_view.xml
  account_tax_balance/wizard/__init__.py
  account_tax_balance/wizard/open_tax_balances.py
  account_tax_balance/wizard/open_tax_balances_view.xml
  setup/account_tax_balance/odoo/addons/account_tax_balance
  setup/account_tax_balance/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#942 [13.0][FIX] account_financial_report: Set the correct value of column 'Cumul cur.' in general ledger
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: approved, bot is merging ⏳

#954 [13.0][FIX] account_financial_report: Prevent error in general_ledger if foreign_currency is not set.
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: approved, bot is merging ⏳

#955 [14.0][FIX] account_financial_report: Show records in general ledger when not grouped.
  account_financial_report/report/general_ledger.py
  account_financial_report/wizard/general_ledger_wizard.py
Labels: approved, bot is merging ⏳

#958 [15.0][FIX] account_financial_report: Show records in general ledger when not grouped.
  account_financial_report/report/general_ledger.py
  account_financial_report/wizard/general_ledger_wizard.py
Labels: needs review, approved, bot is merging ⏳

#960 [13.0][FIX] account_financial_report: Show records in general ledger when not grouped.
  account_financial_report/report/general_ledger.py
  account_financial_report/wizard/general_ledger_wizard.py
Labels: needs review, approved, bot is merging ⏳
