Repository OCA/account-financial-reporting, pull requests merged in 2022-12, with the labels that each got.

#962 [15.0][FIX] account_financial_report: Run compute in multi
  account_financial_report/models/account_group.py
Labels: bot is merging ⏳

#965 [15.0][FIX] account_financial_report: Trial Balance with 'hide account at 0'
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/trial_balance.py
  account_financial_report/report/trial_balance_xlsx.py
  account_financial_report/tests/test_trial_balance.py
  account_financial_report/wizard/trial_balance_wizard.py
  account_financial_report/wizard/trial_balance_wizard_view.xml
Labels: approved, bot is merging ⏳

#949 [14.0][FIX] account_financial_report: Set the correct value of column 'Cumul cur.' in general ledger
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: bot is merging ⏳

#966 [15.0][FIX] account_financial_report: Set the correct value of column 'Cumul cur.' in general ledger
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: bot is merging ⏳

#969 [14.0][FIX] account_financial_report: generate ledger document
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: bot is merging ⏳

#951 [13.0][IMP] account_financial_report: extensibility: ml fields
  account_financial_report/report/abstract_report.py
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/aged_partner_balance.py
  account_financial_report/report/general_ledger.py
  account_financial_report/report/open_items.py
  account_financial_report/report/vat_report.py
Labels: approved, bot is merging ⏳

#982 [16.0][FIX] account_financial_report: generate ledger document
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: bot is merging ⏳

#976 [15.0][IMP] account_financial_report: change report access groups to only 'Show Full Accounting Features'
  account_financial_report/menuitems.xml
Labels: approved, ready to merge, bot is merging ⏳

#973 [14.0][IMP] account_financial_report: change report access groups to only 'Show Full Accounting Features'
  account_financial_report/menuitems.xml
Labels: approved, ready to merge, bot is merging ⏳

#974 [13.0][IMP] account_financial_report: change report access groups to only 'Show Full Accounting Features'
  account_financial_report/menuitems.xml
Labels: approved, ready to merge, bot is merging ⏳
