Repository OCA/account-financial-reporting, pull requests merged in 2022-05, with the labels that each got.

#878 [13.0][FIX] *: Switch license + website
  account_financial_report/__manifest__.py
  mis_builder_cash_flow/__manifest__.py
Labels: bot is merging ⏳

#877 [13.0][MIG] mis_template_financial_report: Migration to 13.0
  mis_template_financial_report/README.rst
  mis_template_financial_report/__init__.py
  mis_template_financial_report/__manifest__.py
  mis_template_financial_report/data/mis_report.xml
  mis_template_financial_report/data/mis_report_kpi.xml
  mis_template_financial_report/data/mis_report_style.xml
  mis_template_financial_report/data/mis_report_subreport.xml
  mis_template_financial_report/i18n/fr.po
  mis_template_financial_report/i18n/mis_template_financial_report.pot
  mis_template_financial_report/models/__init__.py
  mis_template_financial_report/models/mis_report_instance.py
  mis_template_financial_report/readme/CONFIGURE.rst
  mis_template_financial_report/readme/CONTRIBUTORS.rst
  mis_template_financial_report/readme/DESCRIPTION.rst
  mis_template_financial_report/readme/ROADMAP.rst
  mis_template_financial_report/readme/USAGE.rst
  mis_template_financial_report/static/description/icon.png
  mis_template_financial_report/static/description/index.html
  mis_template_financial_report/static/src/css/mis_template_financial_report.css
  mis_template_financial_report/static/src/css/report.css
  mis_template_financial_report/static/src/xml/mis_template_financial_report.xml
  mis_template_financial_report/tests/__init__.py
  mis_template_financial_report/tests/test_mis_template_financial_report.py
  mis_template_financial_report/views/mis_report_instance_views.xml
  mis_template_financial_report/views/templates.xml
  setup/mis_template_financial_report/odoo/addons/mis_template_financial_report
  setup/mis_template_financial_report/setup.py
Labels: needs review, approved, bot is merging ⏳

#864 [13.0][FIX] account_financial_report: Computed hierarchy get groups from account code
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/trial_balance.py
  account_financial_report/report/trial_balance_xlsx.py
  account_financial_report/wizard/trial_balance_wizard_view.xml
Labels: needs review, approved, bot is merging ⏳

#880 [13.0][FIX] account_financial_report: Tests post_install to avoid CI issues
  account_financial_report/tests/test_trial_balance.py
Labels: bot is merging ⏳

#881 [14.0][FIX] account_financial_report: Memory problems setting filters
  account_financial_report/wizard/aged_partner_balance_wizard.py
  account_financial_report/wizard/general_ledger_wizard.py
  account_financial_report/wizard/open_items_wizard.py
  account_financial_report/wizard/trial_balance_wizard.py
Labels: approved, bot is merging ⏳
