Repository OCA/account-financial-reporting, pull requests merged in 2023-01, with the labels that each got.

#984 [14.0][FIX] account_financial_report: Set acc_id key in total_amount if not exist (trial balance)
  account_financial_report/report/trial_balance.py
Labels: approved, bot is merging ⏳

#971 [15.0][IMP][FWD] account_financial_report: extensibility: ml fields
  account_financial_report/report/abstract_report.py
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/aged_partner_balance.py
  account_financial_report/report/general_ledger.py
  account_financial_report/report/open_items.py
  account_financial_report/report/vat_report.py
Labels: approved, ready to merge, bot is merging ⏳

#987 [14.0][FIX] partner_statement: date in prior balance (detailed statement)
  partner_statement/views/outstanding_statement.xml
Labels: bot is merging ⏳

#990 [16.0][IMP] account_financial_report: extensibility xlsx: allow to use other column types (forward port)
  account_financial_report/report/abstract_report.py
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/aged_partner_balance.py
  account_financial_report/report/general_ledger.py
  account_financial_report/report/open_items.py
  account_financial_report/report/vat_report.py
Labels: bot is merging ⏳

#985 [14.0][FIX] account_financial_report: General ledger changes
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: approved, bot is merging ⏳

#988 [14.0][FIX] partner_statement: several fixes
  partner_statement/report/activity_statement.py
  partner_statement/report/activity_statement_xlsx.py
  partner_statement/report/detailed_activity_statement.py
  partner_statement/report/detailed_activity_statement_xlsx.py
  partner_statement/report/outstanding_statement.py
  partner_statement/report/outstanting_statement_xlsx.py
  partner_statement/report/report_statement_common.py
  partner_statement/views/activity_statement.xml
  partner_statement/views/outstanding_statement.xml
  partner_statement/wizard/detailed_activity_statement_wizard.py
  partner_statement/wizard/statement_wizard.xml
Labels: approved, bot is merging ⏳

#993 [15.0][FIX] account_financial_report: General ledger changes
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: approved, bot is merging ⏳

#995 [16.0][FIX] account_financial_report: General ledger changes
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: bot is merging ⏳

#992 [14.0][IMP+FIX] account_financial_report: Trial balance changes
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/trial_balance.py
  account_financial_report/report/trial_balance_xlsx.py
Labels: approved, bot is merging ⏳

#997 [15.0][IMP+FIX] account_financial_report: Trial balance changes
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/trial_balance.py
  account_financial_report/report/trial_balance_xlsx.py
Labels: approved, bot is merging ⏳

#998 [16.0][IMP+FIX] account_financial_report: Trial balance changes
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/trial_balance.py
  account_financial_report/report/trial_balance_xlsx.py
Labels: approved, bot is merging ⏳

#999 [15.0][MIG] account_sale_stock_report_non_billed: Migration to version 15.0
  account_sale_stock_report_non_billed/README.rst
  account_sale_stock_report_non_billed/__init__.py
  account_sale_stock_report_non_billed/__manifest__.py
  account_sale_stock_report_non_billed/i18n/account_sale_stock_report_non_billed.pot
  account_sale_stock_report_non_billed/i18n/es.po
  account_sale_stock_report_non_billed/models/__init__.py
  account_sale_stock_report_non_billed/models/account_move_line.py
  account_sale_stock_report_non_billed/models/res_company.py
  account_sale_stock_report_non_billed/models/res_config_settings.py
  account_sale_stock_report_non_billed/models/stock_move.py
  account_sale_stock_report_non_billed/readme/CONTRIBUTORS.rst
  account_sale_stock_report_non_billed/readme/DESCRIPTION.rst
  account_sale_stock_report_non_billed/readme/USAGE.rst
  account_sale_stock_report_non_billed/security/ir.model.access.csv
  account_sale_stock_report_non_billed/static/description/icon.png
  account_sale_stock_report_non_billed/static/description/index.html
  account_sale_stock_report_non_billed/tests/__init__.py
  account_sale_stock_report_non_billed/tests/test_account_sale_stock_report_non_billed.py
  account_sale_stock_report_non_billed/views/res_config_settings_views.xml
  account_sale_stock_report_non_billed/views/stock_move_non_billed_views.xml
  account_sale_stock_report_non_billed/wizard/__init__.py
  account_sale_stock_report_non_billed/wizard/account_sale_stock_report_non_billed_wiz.py
  account_sale_stock_report_non_billed/wizard/account_sale_stock_report_non_billed_wiz_views.xml
  setup/account_sale_stock_report_non_billed/odoo/addons/account_sale_stock_report_non_billed
  setup/account_sale_stock_report_non_billed/setup.py
Labels: approved, bot is merging ⏳
