Repository OCA/account-financial-reporting, pull requests merged in 2023-02, with the labels that each got.

#1002 [15.0][MIG] account_purchase_stock_report_non_billed: Migration to version 15.0
  account_purchase_stock_report_non_billed/README.rst
  account_purchase_stock_report_non_billed/__init__.py
  account_purchase_stock_report_non_billed/__manifest__.py
  account_purchase_stock_report_non_billed/i18n/account_purchase_stock_report_non_billed.pot
  account_purchase_stock_report_non_billed/i18n/es.po
  account_purchase_stock_report_non_billed/models/__init__.py
  account_purchase_stock_report_non_billed/models/stock_move.py
  account_purchase_stock_report_non_billed/readme/CONTRIBUTORS.rst
  account_purchase_stock_report_non_billed/readme/DESCRIPTION.rst
  account_purchase_stock_report_non_billed/readme/USAGE.rst
  account_purchase_stock_report_non_billed/static/description/icon.png
  account_purchase_stock_report_non_billed/static/description/index.html
  account_purchase_stock_report_non_billed/tests/__init__.py
  account_purchase_stock_report_non_billed/tests/test_account_purchase_stock_report_non_billed.py
  account_purchase_stock_report_non_billed/wizard/__init__.py
  account_purchase_stock_report_non_billed/wizard/account_sale_stock_report_non_billed_wiz.py
  account_sale_stock_report_non_billed/models/account_move_line.py
  setup/account_purchase_stock_report_non_billed/odoo/addons/account_purchase_stock_report_non_billed
  setup/account_purchase_stock_report_non_billed/setup.py
Labels: approved, bot is merging ⏳

#1006 [14.0][FIX] partner_statement: multi-company bug (minor fix)
  partner_statement/report/activity_statement.py
Labels: bot is merging ⏳

#1003 [16.0][FIX] account_financial_report: endless installation
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  account_financial_report/models/account_group.py
Labels: needs review, approved, bot is merging ⏳

#1007 [14.0][FIX] partner_statement: activity aggregations
  partner_statement/report/activity_statement.py
Labels: bot is merging ⏳

#926 [14.0][FIX] account_financial_report: open_items
  account_financial_report/report/abstract_report.py
  account_financial_report/report/aged_partner_balance.py
  account_financial_report/report/open_items.py
Labels: approved, bot is merging ⏳

#1010 [14.0][IMP] partner_statement: ref in activity statement lines
  partner_statement/report/activity_statement.py
Labels: approved, bot is merging ⏳

#1012 [15.0][MIG] mis_template_financial_report: Migration to version 15.0
  mis_template_financial_report/README.rst
  mis_template_financial_report/__init__.py
  mis_template_financial_report/__manifest__.py
  mis_template_financial_report/data/mis_report.xml
  mis_template_financial_report/data/mis_report_kpi.xml
  mis_template_financial_report/data/mis_report_style.xml
  mis_template_financial_report/data/mis_report_subreport.xml
  mis_template_financial_report/i18n/es.po
  mis_template_financial_report/i18n/fi.po
  mis_template_financial_report/i18n/fr.po
  mis_template_financial_report/i18n/mis_template_financial_report.pot
  mis_template_financial_report/models/__init__.py
  mis_template_financial_report/models/mis_report_instance.py
  mis_template_financial_report/readme/CONFIGURE.rst
  mis_template_financial_report/readme/CONTRIBUTORS.rst
  mis_template_financial_report/readme/DESCRIPTION.rst
  mis_template_financial_report/readme/ROADMAP.rst
  mis_template_financial_report/readme/USAGE.rst
  mis_template_financial_report/readme/newsfragments/.gitkeep
  mis_template_financial_report/static/description/icon.png
  mis_template_financial_report/static/description/index.html
  mis_template_financial_report/static/src/css/mis_template_financial_report.css
  mis_template_financial_report/static/src/css/report.css
  mis_template_financial_report/static/src/xml/mis_template_financial_report.xml
  mis_template_financial_report/tests/__init__.py
  mis_template_financial_report/tests/test_mis_template_financial_report.py
  mis_template_financial_report/views/mis_report_instance_views.xml
  mis_template_financial_report/views/templates.xml
  setup/mis_template_financial_report/odoo/addons/mis_template_financial_report
  setup/mis_template_financial_report/setup.py
Labels: needs review, approved, bot is merging ⏳

#1014 [16.0][IMP] account_financial_report: Remove amount_different_company_currency type from xlsx
  account_financial_report/report/abstract_report.py
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/general_ledger_xlsx.py
Labels: bot is merging ⏳
