Repository OCA/account-financial-reporting, pull requests merged in 2023-09, with the labels that each got.

#1058 [15.0][FIX] account_sale_stock_report_non_billed: Date can't be comparated with bool
  account_sale_stock_report_non_billed/models/stock_move.py
  account_sale_stock_report_non_billed/wizard/account_sale_stock_report_non_billed_wiz.py
Labels: bot is merging ⏳

#953 [13.0][FIX] account_sale_stock_report_non_billed: Date can't be comparated with bool
  account_sale_stock_report_non_billed/models/stock_move.py
  account_sale_stock_report_non_billed/wizard/account_sale_stock_report_non_billed_wiz.py
Labels: approved, bot is merging ⏳

#1065 [15.0][FIX] account_sale_stock_report_non_billed: Date can't be comparated with bool
  account_sale_stock_report_non_billed/models/stock_move.py
  account_sale_stock_report_non_billed/wizard/account_sale_stock_report_non_billed_wiz.py
Labels: bot is merging ⏳

#1066 [13.0][FIX] account_sale_stock_report_non_billed: Extra exception conditions
  account_sale_stock_report_non_billed/models/stock_move.py
Labels: approved, bot is merging ⏳

#1067 [15.0][FIX] account_sale_stock_report_non_billed: Extra exception conditions
  account_sale_stock_report_non_billed/models/stock_move.py
Labels: bot is merging ⏳

#1068 [16.0][FIX] account_financial_report: Fix currency bug on trial balance report
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/trial_balance.py
Labels: approved, bot is merging ⏳

#1049 [16.0][MIG] mis_builder_cash_flow: Migration to version 16.0
  mis_builder_cash_flow/README.rst
  mis_builder_cash_flow/__init__.py
  mis_builder_cash_flow/__manifest__.py
  mis_builder_cash_flow/data/mis_report.xml
  mis_builder_cash_flow/data/mis_report_instance.xml
  mis_builder_cash_flow/data/mis_report_style.xml
  mis_builder_cash_flow/i18n/ca.po
  mis_builder_cash_flow/i18n/ca_ES.po
  mis_builder_cash_flow/i18n/es.po
  mis_builder_cash_flow/i18n/es_AR.po
  mis_builder_cash_flow/i18n/it.po
  mis_builder_cash_flow/i18n/mis_builder_cash_flow.pot
  mis_builder_cash_flow/i18n/nl.po
  mis_builder_cash_flow/i18n/pt.po
  mis_builder_cash_flow/models/__init__.py
  mis_builder_cash_flow/models/account_account.py
  mis_builder_cash_flow/models/mis_cash_flow_forecast_line.py
  mis_builder_cash_flow/readme/CONTRIBUTORS.rst
  mis_builder_cash_flow/readme/DESCRIPTION.rst
  mis_builder_cash_flow/readme/ROADMAP.rst
  mis_builder_cash_flow/readme/USAGE.rst
  mis_builder_cash_flow/report/__init__.py
  mis_builder_cash_flow/report/mis_cash_flow.py
  mis_builder_cash_flow/report/mis_cash_flow_views.xml
  mis_builder_cash_flow/security/mis_cash_flow_security.xml
  mis_builder_cash_flow/static/description/icon.png
  mis_builder_cash_flow/static/description/index.html
  mis_builder_cash_flow/tests/__init__.py
  mis_builder_cash_flow/tests/test_cash_flow.py
  mis_builder_cash_flow/views/account_account_views.xml
  mis_builder_cash_flow/views/mis_cash_flow_forecast_line_views.xml
  setup/mis_builder_cash_flow/odoo/addons/mis_builder_cash_flow
  setup/mis_builder_cash_flow/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1073 [FIX] account_financial_report: Empty format
  account_financial_report/report/abstract_report_xlsx.py
Labels: bot is merging ⏳

#1074 [15.0][FIX] account_financial_report: Empty format
  account_financial_report/report/abstract_report_xlsx.py
Labels: bot is merging ⏳
