Repository OCA/account-financial-reporting, pull requests merged in 2023-04, with the labels that each got.

#1029 [14.0][FIX] account_financial_report fix to take the id of the currency if …
  account_financial_report/report/abstract_report.py
Labels: approved, ready to merge, bot is merging ⏳

#1030 [FIX] account_financial_report fix to take the id of the currency if …
  account_financial_report/report/abstract_report.py
Labels: bot is merging ⏳

#1032 [13.0][IMP] account_financial_report: Show move_name in entry column from general ledger report
  account_financial_report/report/general_ledger.py
Labels: approved, bot is merging ⏳

#1034 [14.0][IMP] account_financial_report: Show move_name in entry column from general ledger report
  account_financial_report/report/general_ledger.py
Labels: approved, bot is merging ⏳

#1036 [15.0][IMP] account_financial_report: Show move_name in entry column from general ledger report
  account_financial_report/report/general_ledger.py
Labels: approved, bot is merging ⏳

#1037 [16.0][FIX] account_financial_report, Fix report links with domain
  account_financial_report/__manifest__.py
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/report/templates/journal_ledger.xml
  account_financial_report/report/templates/open_items.xml
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/templates/vat_report.xml
  account_financial_report/static/src/js/report.esm.js
  account_financial_report/static/src/js/report.js
  account_financial_report/static/src/js/report_action.esm.js
Labels: approved, bot is merging ⏳

#1038 [16.0][IMP] account_financial_report: Show move_name in entry column from general ledger report
  account_financial_report/report/general_ledger.py
Labels: approved, bot is merging ⏳
