Repository OCA/account-financial-reporting, pull requests merged in 2023-05, with the labels that each got.

#1033 [14.0][FIX] account_financial_report: Prevent error related to currency from General ledger
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: approved, ready to merge, bot is merging ⏳

#1041 [16.0][FIX] account_financial_report: Prevent error related to currency fro…
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: needs review, bot is merging ⏳

#1044 [15.0][FIX] account_financial_report: fixing calculation bug
  account_financial_report/report/abstract_report.py
Labels: bot is merging ⏳

#1042 [15.0][FIX] account_financial_report: Prevent error related to currency from General ledger
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: bot is merging ⏳
