Repository OCA/account-financial-reporting, pull requests merged in 2023-03, with the labels that each got.

#1017 [14.0][FIX] partner_statement: use partner lang in xlsx reports
  partner_statement/report/activity_statement_xlsx.py
  partner_statement/report/detailed_activity_statement_xlsx.py
  partner_statement/report/outstanting_statement_xlsx.py
Labels: bot is merging ⏳

#1019 [14.0][FIX] account_financial_report: Assure the aml order
  account_financial_report/report/general_ledger.py
Labels: approved

#1020 [15.0][FIX] account_financial_report: Assure the aml order
  account_financial_report/report/general_ledger.py
Labels: approved, bot is merging ⏳

#1021 [16.0][FIX] account_financial_report: Assure the aml order
  account_financial_report/report/general_ledger.py
Labels: bot is merging ⏳

#1023 [16.0][account_financial_report][FWD]Fix account group styling in qweb and xlsx
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/templates/trial_balance.xml
Labels: bot is merging ⏳

#1024 [15.0][FIX] account_financial_report: Account group styling in qweb and xlsx
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/templates/trial_balance.xml
Labels: bot is merging ⏳

#1025 [14.0] [FIX] account_financial_report: Fix wrong field `amount_currency` in `account.partial.reconcile`
  account_financial_report/report/aged_partner_balance.py
Labels: approved

#1027 [16.0][FIX] account_financial_report (forward port)
  account_financial_report/report/abstract_report.py
  account_financial_report/report/aged_partner_balance.py
  account_financial_report/report/open_items.py
Labels: bot is merging ⏳
