Repository OCA/account-financial-reporting, pull requests merged in 2024-05, with the labels that each got.

#1149 [16.0][FIX] account_financial_report: fix error false due_date
  account_financial_report/report/aged_partner_balance.py
Labels: bot is merging ⏳

#1150 [15.0][FIX] account_financial_report: fix error false due_date
  account_financial_report/report/aged_partner_balance.py
Labels: bot is merging ⏳

#1152 [17.0][FWD] account_financial_report: fix error false due_date
  account_financial_report/report/aged_partner_balance.py
Labels: approved, bot is merging ⏳

#1158 [FIX]-Can not print xlsx report for Activity Statement, Outstanding S…
  partner_statement/wizard/activity_statement_wizard.py
  partner_statement/wizard/detailed_activity_statement_wizard.py
  partner_statement/wizard/outstanding_statement_wizard.py
Labels: approved, bot is merging ⏳

#1157 [17.0][FWD][FIX] account_financial_report: aged partner compute due date
  account_financial_report/report/aged_partner_balance.py
Labels: bot is merging ⏳

#1155 [16.0][FIX] account_financial_report: aged partner compute due date
  account_financial_report/report/aged_partner_balance.py
Labels: bot is merging ⏳

#1156 [15.0][FWD][FIX] account_financial_report: aged partner compute due date
  account_financial_report/report/aged_partner_balance.py
Labels: bot is merging ⏳

#1161 [16.0][FIX] partner_statement: can not print xlsx reports (forward port)
  partner_statement/wizard/activity_statement_wizard.py
  partner_statement/wizard/detailed_activity_statement_wizard.py
  partner_statement/wizard/outstanding_statement_wizard.py
Labels: bot is merging ⏳

#1162 [14.0][FIX] partner_statement: can not print xlsx reports (backport)
  partner_statement/wizard/activity_statement_wizard.py
  partner_statement/wizard/detailed_activity_statement_wizard.py
  partner_statement/wizard/outstanding_statement_wizard.py
Labels: bot is merging ⏳

#947 Fix line "name" None breaking comparison
  partner_statement/report/activity_statement_xlsx.py
Labels: approved, bot is merging ⏳, stale

#1089 [14.0][FIX] account_financial_report - show all accounts when group by none
  account_financial_report/report/general_ledger.py
Labels: approved, bot is merging ⏳, stale

#1148 [15.0][IMP] account_financial_report: Change font size
  account_financial_report/report/templates/aged_partner_balance.xml
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/report/templates/journal_ledger.xml
  account_financial_report/report/templates/layouts.xml
  account_financial_report/report/templates/open_items.xml
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/templates/vat_report.xml
  account_financial_report/static/src/css/report_html.css
Labels: approved, ready to merge, bot is merging ⏳

#1170 [16.0][IMP] account_financial_report: Change font size
  account_financial_report/report/templates/aged_partner_balance.xml
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/report/templates/journal_ledger.xml
  account_financial_report/report/templates/layouts.xml
  account_financial_report/report/templates/open_items.xml
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/templates/vat_report.xml
  account_financial_report/static/src/css/report_html.css
Labels: approved, bot is merging ⏳

#1171 [17.0][IMP] account_financial_report: Change font size
  account_financial_report/report/templates/aged_partner_balance.xml
  account_financial_report/report/templates/general_ledger.xml
  account_financial_report/report/templates/journal_ledger.xml
  account_financial_report/report/templates/layouts.xml
  account_financial_report/report/templates/open_items.xml
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/templates/vat_report.xml
  account_financial_report/static/src/css/report_html.css
Labels: approved, bot is merging ⏳

#1164 [15.0][FIX] partner_statement: don't consider reconciled lines outside date range
  partner_statement/report/activity_statement_xlsx.py
  partner_statement/report/detailed_activity_statement_xlsx.py
  partner_statement/report/outstanting_statement_xlsx.py
  partner_statement/report/report_statement_common.py
  partner_statement/static/src/scss/layout_statement.scss
  partner_statement/views/activity_statement.xml
  partner_statement/wizard/activity_statement_wizard.py
  partner_statement/wizard/detailed_activity_statement_wizard.py
  partner_statement/wizard/outstanding_statement_wizard.py
Labels: bot is merging ⏳

#1181 [15.0][FIX] partner_statement: tests date relativity
  partner_statement/tests/test_activity_statement.py
Labels: bot is merging ⏳

#1177 [16.0][FIX] partner_statement: don't consider reconciled lines outside date range (forward port)
  partner_statement/report/activity_statement_xlsx.py
  partner_statement/report/detailed_activity_statement_xlsx.py
  partner_statement/report/outstanting_statement_xlsx.py
  partner_statement/report/report_statement_common.py
  partner_statement/static/src/scss/layout_statement.scss
  partner_statement/tests/test_activity_statement.py
  partner_statement/views/activity_statement.xml
  partner_statement/wizard/activity_statement_wizard.py
  partner_statement/wizard/detailed_activity_statement_wizard.py
  partner_statement/wizard/outstanding_statement_wizard.py
Labels: bot is merging ⏳
