Repository OCA/account-financial-reporting, pull requests merged in 2024-02, with the labels that each got.

#1105 [16.0][FIX] account_financial_report: optimize computation of analytic accounts
  account_financial_report/models/account_move_line.py
Labels: needs review, approved, bot is merging ⏳

#1087 [17.0][MIG] account_tax_balance: Migration to 17.0
  account_tax_balance/README.rst
  account_tax_balance/__init__.py
  account_tax_balance/__manifest__.py
  account_tax_balance/hooks.py
  account_tax_balance/i18n/account_tax_balance.pot
  account_tax_balance/i18n/ca.po
  account_tax_balance/i18n/de.po
  account_tax_balance/i18n/es.po
  account_tax_balance/i18n/es_AR.po
  account_tax_balance/i18n/fr.po
  account_tax_balance/i18n/fr_FR.po
  account_tax_balance/i18n/hr_HR.po
  account_tax_balance/i18n/it.po
  account_tax_balance/i18n/nl.po
  account_tax_balance/i18n/nl_NL.po
  account_tax_balance/i18n/pt.po
  account_tax_balance/i18n/pt_BR.po
  account_tax_balance/i18n/ro.po
  account_tax_balance/models/__init__.py
  account_tax_balance/models/account_move.py
  account_tax_balance/models/account_move_line.py
  account_tax_balance/models/account_tax.py
  account_tax_balance/pyproject.toml
  account_tax_balance/readme/CONTRIBUTORS.md
  account_tax_balance/readme/DESCRIPTION.md
  account_tax_balance/readme/USAGE.md
  account_tax_balance/security/ir.model.access.csv
  account_tax_balance/static/description/icon.png
  account_tax_balance/static/description/index.html
  account_tax_balance/static/description/tax_balance.png
  account_tax_balance/tests/__init__.py
  account_tax_balance/tests/test_account_tax_balance.py
  account_tax_balance/views/account_move_view.xml
  account_tax_balance/views/account_tax_view.xml
  account_tax_balance/wizard/__init__.py
  account_tax_balance/wizard/open_tax_balances.py
  account_tax_balance/wizard/open_tax_balances_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1098 [15.0][FIX]account_financial_report: missing accounts
  account_financial_report/tests/test_trial_balance.py
  account_financial_report/wizard/trial_balance_wizard.py
Labels: approved, ready to merge, bot is merging ⏳

#1110 [14.0][IMP] account_financial_report: Add Missing Partner support in trial balance
  account_financial_report/report/general_ledger.py
  account_financial_report/report/open_items.py
  account_financial_report/report/trial_balance.py
Labels: approved, bot is merging ⏳

#1113 [15.0][IMP] account_financial_report: Add Missing Partner support in trial balance
  account_financial_report/report/general_ledger.py
  account_financial_report/report/open_items.py
  account_financial_report/report/trial_balance.py
Labels: approved, bot is merging ⏳

#1114 [16.0][IMP] account_financial_report: Add Missing Partner support in trial balance
  account_financial_report/report/general_ledger.py
  account_financial_report/report/open_items.py
  account_financial_report/report/trial_balance.py
Labels: approved, bot is merging ⏳

#1112 [16.0][FIX]account_financial_report: missing accounts
  account_financial_report/tests/test_trial_balance.py
  account_financial_report/wizard/trial_balance_wizard.py
Labels: bot is merging ⏳
