Repository OCA/account-financial-reporting, pull requests merged in 2024-09, with the labels that each got.

#1219 [17.0][FIX] account_financial_report: fix ValueError
  account_financial_report/models/account_move_line.py
Labels: approved, bot is merging ⏳

#1204 [16.0][MIG] account_financial_report_sale: Migration to 16.0
  account_financial_report_sale/README.rst
  account_financial_report_sale/__init__.py
  account_financial_report_sale/__manifest__.py
  account_financial_report_sale/i18n/account_financial_report_sale.pot
  account_financial_report_sale/i18n/es.po
  account_financial_report_sale/readme/CONTRIBUTORS.rst
  account_financial_report_sale/readme/DESCRIPTION.rst
  account_financial_report_sale/readme/USAGE.rst
  account_financial_report_sale/report/__init__.py
  account_financial_report_sale/report/open_items.py
  account_financial_report_sale/static/description/icon.png
  account_financial_report_sale/static/description/index.html
  account_financial_report_sale/tests/__init__.py
  account_financial_report_sale/tests/test_open_items.py
  account_financial_report_sale/wizard/__init__.py
  account_financial_report_sale/wizard/open_items_wizard.py
  setup/account_financial_report_sale/odoo/addons/account_financial_report_sale
  setup/account_financial_report_sale/setup.py
Labels: bot is merging ⏳

#1183 [16.0][MIG] account_sale_stock_report_non_billed
  account_sale_stock_report_non_billed/README.rst
  account_sale_stock_report_non_billed/__init__.py
  account_sale_stock_report_non_billed/__manifest__.py
  account_sale_stock_report_non_billed/i18n/account_sale_stock_report_non_billed.pot
  account_sale_stock_report_non_billed/i18n/es.po
  account_sale_stock_report_non_billed/models/__init__.py
  account_sale_stock_report_non_billed/models/account_move_line.py
  account_sale_stock_report_non_billed/models/res_company.py
  account_sale_stock_report_non_billed/models/res_config_settings.py
  account_sale_stock_report_non_billed/models/stock_move.py
  account_sale_stock_report_non_billed/readme/CONTRIBUTORS.rst
  account_sale_stock_report_non_billed/readme/DESCRIPTION.rst
  account_sale_stock_report_non_billed/readme/USAGE.rst
  account_sale_stock_report_non_billed/security/ir.model.access.csv
  account_sale_stock_report_non_billed/static/description/icon.png
  account_sale_stock_report_non_billed/static/description/index.html
  account_sale_stock_report_non_billed/tests/__init__.py
  account_sale_stock_report_non_billed/tests/test_account_sale_stock_report_non_billed.py
  account_sale_stock_report_non_billed/views/res_config_settings_views.xml
  account_sale_stock_report_non_billed/views/stock_move_non_billed_views.xml
  account_sale_stock_report_non_billed/wizard/__init__.py
  account_sale_stock_report_non_billed/wizard/account_sale_stock_report_non_billed_wiz.py
  account_sale_stock_report_non_billed/wizard/account_sale_stock_report_non_billed_wiz_views.xml
  setup/account_sale_stock_report_non_billed/odoo/addons/account_sale_stock_report_non_billed
  setup/account_sale_stock_report_non_billed/setup.py
Labels: approved, bot is merging ⏳

#1227 [17.0][MIG] mis_builder_cash_flow
  mis_builder_cash_flow/README.rst
  mis_builder_cash_flow/__init__.py
  mis_builder_cash_flow/__manifest__.py
  mis_builder_cash_flow/data/mis_report.xml
  mis_builder_cash_flow/data/mis_report_instance.xml
  mis_builder_cash_flow/data/mis_report_style.xml
  mis_builder_cash_flow/i18n/ca.po
  mis_builder_cash_flow/i18n/ca_ES.po
  mis_builder_cash_flow/i18n/es.po
  mis_builder_cash_flow/i18n/es_AR.po
  mis_builder_cash_flow/i18n/it.po
  mis_builder_cash_flow/i18n/mis_builder_cash_flow.pot
  mis_builder_cash_flow/i18n/nl.po
  mis_builder_cash_flow/i18n/pt.po
  mis_builder_cash_flow/i18n/pt_BR.po
  mis_builder_cash_flow/i18n/sv.po
  mis_builder_cash_flow/migrations/16.0.1.0.0/noupdate_changes.xml
  mis_builder_cash_flow/migrations/16.0.1.0.0/post-migration.py
  mis_builder_cash_flow/models/__init__.py
  mis_builder_cash_flow/models/account_account.py
  mis_builder_cash_flow/models/mis_cash_flow_forecast_line.py
  mis_builder_cash_flow/pyproject.toml
  mis_builder_cash_flow/readme/CONTRIBUTORS.md
  mis_builder_cash_flow/readme/DESCRIPTION.md
  mis_builder_cash_flow/readme/ROADMAP.md
  mis_builder_cash_flow/readme/USAGE.md
  mis_builder_cash_flow/report/__init__.py
  mis_builder_cash_flow/report/mis_cash_flow.py
  mis_builder_cash_flow/report/mis_cash_flow_views.xml
  mis_builder_cash_flow/security/mis_cash_flow_security.xml
  mis_builder_cash_flow/static/description/icon.png
  mis_builder_cash_flow/static/description/index.html
  mis_builder_cash_flow/tests/__init__.py
  mis_builder_cash_flow/tests/test_cash_flow.py
  mis_builder_cash_flow/views/account_account_views.xml
  mis_builder_cash_flow/views/mis_cash_flow_forecast_line_views.xml
Labels: approved, ready to merge, bot is merging ⏳
