Repository OCA/account-financial-reporting, pull requests merged in 2024-01, with the labels that each got.

#989 [15.0][MIG] account_move_line_report_xls: Migration to 15.0
  account_move_line_report_xls/README.rst
  account_move_line_report_xls/__init__.py
  account_move_line_report_xls/__manifest__.py
  account_move_line_report_xls/i18n/account_move_line_report_xls.pot
  account_move_line_report_xls/i18n/fr.po
  account_move_line_report_xls/i18n/nl.po
  account_move_line_report_xls/models/__init__.py
  account_move_line_report_xls/models/account_move_line.py
  account_move_line_report_xls/readme/CONTRIBUTORS.rst
  account_move_line_report_xls/readme/DESCRIPTION.rst
  account_move_line_report_xls/readme/USAGE.rst
  account_move_line_report_xls/report/__init__.py
  account_move_line_report_xls/report/account_move_line_xlsx.py
  account_move_line_report_xls/report/account_move_line_xlsx.xml
  account_move_line_report_xls/static/description/icon.png
  account_move_line_report_xls/static/description/icon.svg
  account_move_line_report_xls/static/description/index.html
  account_move_line_report_xls/tests/__init__.py
  account_move_line_report_xls/tests/test_aml_report_xlsx.py
  setup/account_move_line_report_xls/odoo/addons/account_move_line_report_xls
  setup/account_move_line_report_xls/setup.py
Labels: bot is merging ⏳, stale

#1091 [FIX] [16.0] account_financial_report: fixing bug when calculation of credit is duplicated
  account_financial_report/report/abstract_report.py
Labels: bot is merging ⏳

#1090 [16.0][FIX] account_financial_report: generate ledger document
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: bot is merging ⏳

#1093 [14.0][FIX] account_financial_report: reduce report url
  account_financial_report/report/general_ledger.py
  account_financial_report/wizard/general_ledger_wizard.py
Labels: approved, bot is merging ⏳

#1095 [15.0][FIX] account_financial_report: reduce report urlç
  account_financial_report/report/general_ledger.py
  account_financial_report/wizard/general_ledger_wizard.py
Labels: bot is merging ⏳
