Repository OCA/account-financial-reporting, pull requests merged in 2024-06, with the labels that each got.

#1180 [12.0][FIX] partner_statement: backport fixes from v13 (backport)
  partner_statement/report/activity_statement.py
  partner_statement/report/outstanding_statement.py
  partner_statement/report/report_statement_common.py
  partner_statement/wizard/activity_statement_wizard.py
  partner_statement/wizard/outstanding_statement_wizard.py
Labels: bot is merging ⏳

#1179 [13.0][FIX] partner_statement: backport some fixes from v14 (backport)
  partner_statement/report/activity_statement.py
  partner_statement/report/activity_statement_xlsx.py
  partner_statement/report/outstanding_statement.py
  partner_statement/report/outstanting_statement_xlsx.py
  partner_statement/report/report_statement_common.py
  partner_statement/wizard/activity_statement_wizard.py
  partner_statement/wizard/outstanding_statement_wizard.py
Labels: bot is merging ⏳

#1166 [14.0][IMP] account_financial_report: general ledger filter by account types
  account_financial_report/tests/test_general_ledger.py
  account_financial_report/wizard/general_ledger_wizard.py
  account_financial_report/wizard/general_ledger_wizard_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1144 [16.0][MIG] mis_template_financial_report
  mis_template_financial_report/README.rst
  mis_template_financial_report/__init__.py
  mis_template_financial_report/__manifest__.py
  mis_template_financial_report/data/mis_report.xml
  mis_template_financial_report/data/mis_report_kpi.xml
  mis_template_financial_report/data/mis_report_style.xml
  mis_template_financial_report/data/mis_report_subreport.xml
  mis_template_financial_report/i18n/es.po
  mis_template_financial_report/i18n/fi.po
  mis_template_financial_report/i18n/fr.po
  mis_template_financial_report/i18n/mis_template_financial_report.pot
  mis_template_financial_report/models/__init__.py
  mis_template_financial_report/models/mis_report_instance.py
  mis_template_financial_report/models/mis_report_kpi.py
  mis_template_financial_report/readme/CONFIGURE.rst
  mis_template_financial_report/readme/CONTRIBUTORS.rst
  mis_template_financial_report/readme/DESCRIPTION.rst
  mis_template_financial_report/readme/ROADMAP.rst
  mis_template_financial_report/readme/USAGE.rst
  mis_template_financial_report/readme/newsfragments/.gitkeep
  mis_template_financial_report/static/description/icon.png
  mis_template_financial_report/static/description/index.html
  mis_template_financial_report/static/src/components/mis_report_widget.css
  mis_template_financial_report/static/src/components/mis_report_widget.xml
  mis_template_financial_report/static/src/css/report.css
  mis_template_financial_report/tests/__init__.py
  mis_template_financial_report/tests/test_mis_template_financial_report.py
  mis_template_financial_report/views/mis_report_instance_views.xml
  mis_template_financial_report/views/mis_report_kpi_views.xml
  mis_template_financial_report/views/templates.xml
  setup/mis_template_financial_report/odoo/addons/mis_template_financial_report
  setup/mis_template_financial_report/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#1196 [16.0] [FIX] account_financial_report: Replace 'Camptocamp SA' with 'Camptocamp' in authors
  account_financial_report/__manifest__.py
Labels: bot is merging ⏳

#1195 [15.0] [FIX] account_financial_report: Replace 'Camptocamp SA' with 'Camptocamp' in authors
  account_financial_report/__manifest__.py
Labels: bot is merging ⏳

#1194 [14.0] [FIX] account_financial_report: Replace 'Camptocamp SA' with 'Camptocamp' in authors
  account_financial_report/__manifest__.py
Labels: bot is merging ⏳

#1197 [17.0] [FIX] account_financial_report: Replace 'Camptocamp SA' with 'Camptocamp' in authors
  account_financial_report/__manifest__.py
Labels: bot is merging ⏳

#1189 [13.0][FIX] account_financial_report: Default currency
  account_financial_report/report/abstract_report_xlsx.py
Labels: approved, bot is merging ⏳

#1199 [17.0][MIG] partner_statement: Migration to 17.0
  partner_statement/README.rst
  partner_statement/__init__.py
  partner_statement/__manifest__.py
  partner_statement/i18n/ca.po
  partner_statement/i18n/de.po
  partner_statement/i18n/es.po
  partner_statement/i18n/es_AR.po
  partner_statement/i18n/fr.po
  partner_statement/i18n/hr_HR.po
  partner_statement/i18n/it.po
  partner_statement/i18n/nl.po
  partner_statement/i18n/nl_NL.po
  partner_statement/i18n/partner_statement.pot
  partner_statement/i18n/pt.po
  partner_statement/i18n/pt_BR.po
  partner_statement/i18n/ro.po
  partner_statement/i18n/sv.po
  partner_statement/pyproject.toml
  partner_statement/readme/CONFIGURE.md
  partner_statement/readme/CONTRIBUTORS.md
  partner_statement/readme/DESCRIPTION.md
  partner_statement/readme/HISTORY.md
  partner_statement/readme/ROADMAP.md
  partner_statement/readme/USAGE.md
  partner_statement/report/__init__.py
  partner_statement/report/activity_statement.py
  partner_statement/report/activity_statement_xlsx.py
  partner_statement/report/detailed_activity_statement.py
  partner_statement/report/detailed_activity_statement_xlsx.py
  partner_statement/report/outstanding_statement.py
  partner_statement/report/outstanting_statement_xlsx.py
  partner_statement/report/report_statement_common.py
  partner_statement/security/ir.model.access.csv
  partner_statement/security/statement_security.xml
  partner_statement/static/description/icon.png
  partner_statement/static/description/index.html
  partner_statement/static/src/scss/layout_statement.scss
  partner_statement/tests/__init__.py
  partner_statement/tests/test_activity_statement.py
  partner_statement/tests/test_outstanding_statement.py
  partner_statement/tests/test_res_config_settings.py
  partner_statement/views/activity_statement.xml
  partner_statement/views/aging_buckets.xml
  partner_statement/views/detailed_activity_statement.xml
  partner_statement/views/outstanding_statement.xml
  partner_statement/views/res_config_settings.xml
  partner_statement/wizard/__init__.py
  partner_statement/wizard/activity_statement_wizard.py
  partner_statement/wizard/detailed_activity_statement_wizard.py
  partner_statement/wizard/outstanding_statement_wizard.py
  partner_statement/wizard/res_config_settings.py
  partner_statement/wizard/statement_common.py
  partner_statement/wizard/statement_wizard.xml
Labels: approved, bot is merging ⏳
