Repository OCA/account-financial-reporting, pull requests merged in 2024-10, with the labels that each got.

#1184 [16.0][MIG] account_purchase_stock_report_non_billed
  account_purchase_stock_report_non_billed/README.rst
  account_purchase_stock_report_non_billed/__init__.py
  account_purchase_stock_report_non_billed/__manifest__.py
  account_purchase_stock_report_non_billed/i18n/account_purchase_stock_report_non_billed.pot
  account_purchase_stock_report_non_billed/i18n/es.po
  account_purchase_stock_report_non_billed/models/__init__.py
  account_purchase_stock_report_non_billed/models/stock_move.py
  account_purchase_stock_report_non_billed/readme/CONTRIBUTORS.rst
  account_purchase_stock_report_non_billed/readme/DESCRIPTION.rst
  account_purchase_stock_report_non_billed/readme/USAGE.rst
  account_purchase_stock_report_non_billed/static/description/icon.png
  account_purchase_stock_report_non_billed/static/description/index.html
  account_purchase_stock_report_non_billed/tests/__init__.py
  account_purchase_stock_report_non_billed/tests/test_account_purchase_stock_report_non_billed.py
  account_purchase_stock_report_non_billed/wizard/__init__.py
  account_purchase_stock_report_non_billed/wizard/account_sale_stock_report_non_billed_wiz.py
  setup/account_purchase_stock_report_non_billed/odoo/addons/account_purchase_stock_report_non_billed
  setup/account_purchase_stock_report_non_billed/setup.py
Labels: bot is merging ⏳, stale

#1232 [16.0][FIX] account_financial_report: Display the values of Amount cur. + Cumul cur. values in general ledger only if necessary
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: approved, bot is merging ⏳

#1234 [17.0][FIX] account_financial_report: Display the values of Amount cur. + Cumul cur. values in general ledger only if necessary
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: approved, bot is merging ⏳

#1235 [15.0][FIX] account_financial_report: Display the values of Amount cur. + Cumul cur. values in general ledger only if necessary
  account_financial_report/report/general_ledger_xlsx.py
Labels: approved, bot is merging ⏳

#1151 [15.0][IMP] account_financial_report: Add grouping by analytical account in Trial balance
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/trial_balance.py
  account_financial_report/report/trial_balance_xlsx.py
  account_financial_report/wizard/trial_balance_wizard.py
  account_financial_report/wizard/trial_balance_wizard_view.xml
Labels: bot is merging ⏳

#914 [14.0][FIX] account_financial_report: partner trial balance: sort by partner name
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/trial_balance.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1238 [14.0][FIX] account_financial_report: in XLSX report, display null ending balance
  account_financial_report/report/abstract_report_xlsx.py
Labels: approved, bot is merging ⏳

#1244 [16][FIX] account_financial_report : fix wizard model names sent to qweb reports for vat and aged balance reports
  account_financial_report/report/aged_partner_balance.py
  account_financial_report/report/vat_report.py
Labels: approved, bot is merging ⏳

#1245 [17][FIX] account_financial_report : fix wizard model names sent to qweb reports for vat and aged balance reports
  account_financial_report/report/aged_partner_balance.py
  account_financial_report/report/vat_report.py
Labels: approved, bot is merging ⏳

#1242 [14.0][FIX] account_financial_report: Open Items report now sorted by account code
  account_financial_report/report/open_items.py
Labels: approved, bot is merging ⏳

#1239 [17.0] Forward port 4 fixes from v14 to v17
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/open_items.py
  account_financial_report/report/trial_balance.py
Labels: approved, bot is merging ⏳

#1240 [16.0] Forward port 4 fixes from v14 to v16
  account_financial_report/report/abstract_report_xlsx.py
  account_financial_report/report/open_items.py
  account_financial_report/report/trial_balance.py
Labels: approved, bot is merging ⏳
