Repository OCA/account-financial-reporting, pull requests merged in 2024-11, with the labels that each got.

#1247 [15.0][FIX] account_purchase_stock_report_non_billed: consider just done moves
  account_purchase_stock_report_non_billed/models/stock_move.py
Labels: approved, bot is merging ⏳

#1248 [16.0][FIX] account_purchase_stock_report_non_billed: consider just done moves
  account_purchase_stock_report_non_billed/models/stock_move.py
Labels: approved, bot is merging ⏳

#1231 [17.0][MIG] mis_template_financial_report: Migration to 17.0
  mis_template_financial_report/README.rst
  mis_template_financial_report/__init__.py
  mis_template_financial_report/__manifest__.py
  mis_template_financial_report/data/mis_report.xml
  mis_template_financial_report/data/mis_report_kpi.xml
  mis_template_financial_report/data/mis_report_style.xml
  mis_template_financial_report/data/mis_report_subreport.xml
  mis_template_financial_report/i18n/es.po
  mis_template_financial_report/i18n/fi.po
  mis_template_financial_report/i18n/fr.po
  mis_template_financial_report/i18n/it.po
  mis_template_financial_report/i18n/mis_template_financial_report.pot
  mis_template_financial_report/i18n/pt.po
  mis_template_financial_report/models/__init__.py
  mis_template_financial_report/models/mis_report_instance.py
  mis_template_financial_report/models/mis_report_kpi.py
  mis_template_financial_report/pyproject.toml
  mis_template_financial_report/readme/CONFIGURE.md
  mis_template_financial_report/readme/CONTRIBUTORS.md
  mis_template_financial_report/readme/DESCRIPTION.md
  mis_template_financial_report/readme/ROADMAP.md
  mis_template_financial_report/readme/USAGE.md
  mis_template_financial_report/readme/newsfragments/.gitkeep
  mis_template_financial_report/static/description/icon.png
  mis_template_financial_report/static/description/index.html
  mis_template_financial_report/static/src/components/mis_report_widget.css
  mis_template_financial_report/static/src/components/mis_report_widget.xml
  mis_template_financial_report/static/src/css/report.css
  mis_template_financial_report/tests/__init__.py
  mis_template_financial_report/tests/test_mis_template_financial_report.py
  mis_template_financial_report/views/mis_report_instance_views.xml
  mis_template_financial_report/views/mis_report_kpi_views.xml
  mis_template_financial_report/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#1243 [16.0][IMP] account_financial_report: Add grouping by analytical account in Trial balance
  account_financial_report/report/templates/trial_balance.xml
  account_financial_report/report/trial_balance.py
  account_financial_report/report/trial_balance_xlsx.py
  account_financial_report/wizard/trial_balance_wizard.py
  account_financial_report/wizard/trial_balance_wizard_view.xml
Labels: approved, bot is merging ⏳

#1236 [15.0][IMP] account_financial_report: Add Amount cur. to General Ledger totals if the account has not set currency
  account_financial_report/report/general_ledger.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: approved, bot is merging ⏳

#1256 [15.0][FIX] account_financial_report: Avoid error in General ledger if the Show foreign currency checkbox is not checked.
  account_financial_report/report/general_ledger.py
Labels: bot is merging ⏳

#1254 [16.0][IMP] account_financial_report: Add Amount cur. to General Ledger totals if the account has not set currency
  account_financial_report/report/general_ledger.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: approved, bot is merging ⏳

#1257 [17.0][IMP] account_financial_report: Add Amount cur. to General Ledger totals if the account has not set currency
  account_financial_report/report/general_ledger.py
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: approved, bot is merging ⏳
