Repository OCA/account-financial-reporting, pull requests merged in 2025-04, with the labels that each got.

#1304 [18.0][IMP] account_financial_report: Added code for analytic accounts in general leadger
  account_financial_report/report/general_ledger.py
Labels: approved, bot is merging ⏳

#1305 [18.0][FIX] account_financial_report: Correct trial balance domain for analytic accounts
  account_financial_report/report/templates/trial_balance.xml
Labels: approved, bot is merging ⏳

#1303 [17.0][FIX] account_financial_report: Fix error with multiple analytic accounts in distribution
  account_financial_report/report/general_ledger_xlsx.py
  account_financial_report/report/templates/general_ledger.xml
Labels: approved, bot is merging ⏳

#1287 [16.0][PERF] Improve journal ledger performance with lots of lines
  account_financial_report/report/journal_ledger.py
Labels: approved, ready to merge, bot is merging ⏳

#1308 [18.0][FWD][PERF] Improve journal ledger performance with lots of lines
  account_financial_report/report/journal_ledger.py
Labels: bot is merging ⏳

#1307 [17.0][FWD][PERF] Improve journal ledger performance with lots of lines
  account_financial_report/report/journal_ledger.py
Labels: bot is merging ⏳

#1310 [REF] mis_builder_cash_flow: Allow to override query
  mis_builder_cash_flow/report/mis_cash_flow.py
Labels: approved, bot is merging ⏳
