Repository OCA/account-financial-reporting, pull requests merged in 2025-05, with the labels that each got.

#1318 [18.0][FIX] account_financial_report: Amount accumulated several times using hierarchy
  account_financial_report/report/trial_balance.py
Labels: approved, bot is merging ⏳

#1316 [16.0][FIX] account_financial_report: Amount accumulated several times using hierarchy
  account_financial_report/report/trial_balance.py
Labels: approved, bot is merging ⏳

#1317 [17.0][FIX] account_financial_report: Amount accumulated several times using hierarchy
  account_financial_report/report/trial_balance.py
Labels: approved, bot is merging ⏳

#1224 [17.0] [MIG] account_move_line_report_xls: Migration to 17.0
  account_move_line_report_xls/README.rst
  account_move_line_report_xls/__init__.py
  account_move_line_report_xls/__manifest__.py
  account_move_line_report_xls/i18n/account_move_line_report_xls.pot
  account_move_line_report_xls/i18n/es.po
  account_move_line_report_xls/i18n/fr.po
  account_move_line_report_xls/i18n/nl.po
  account_move_line_report_xls/models/__init__.py
  account_move_line_report_xls/models/account_move_line.py
  account_move_line_report_xls/pyproject.toml
  account_move_line_report_xls/readme/CONTRIBUTORS.md
  account_move_line_report_xls/readme/DESCRIPTION.md
  account_move_line_report_xls/readme/ROADMAP.md
  account_move_line_report_xls/readme/USAGE.md
  account_move_line_report_xls/report/__init__.py
  account_move_line_report_xls/report/account_move_line_xlsx.py
  account_move_line_report_xls/report/account_move_line_xlsx.xml
  account_move_line_report_xls/static/description/icon.png
  account_move_line_report_xls/static/description/icon.svg
  account_move_line_report_xls/static/description/index.html
  account_move_line_report_xls/tests/__init__.py
  account_move_line_report_xls/tests/test_aml_report_xlsx.py
Labels: approved, ready to merge, bot is merging ⏳

#1321 [REF] partner_statement: Allow to override XLSX structure
  partner_statement/report/outstanting_statement_xlsx.py
Labels: approved, bot is merging ⏳

#1313 [IMP] partner_statement: Allow to exclude accounts
  partner_statement/report/activity_statement.py
  partner_statement/report/outstanding_statement.py
  partner_statement/report/report_statement_common.py
  partner_statement/tests/test_outstanding_statement.py
  partner_statement/wizard/statement_common.py
  partner_statement/wizard/statement_wizard.xml
Labels: bot is merging ⏳
