Repository OCA/account-financial-reporting, pull requests merged in 2025-07, with the labels that each got.

#1348 [FIX] partner_statement: Create own invoice in test
  partner_statement/tests/test_outstanding_statement.py
Labels: bot is merging ⏳

#1293 [18.0][FIX] account_financial_report: replace old field company_id in account.account by company_ids
  account_financial_report/wizard/general_ledger_wizard.py
  account_financial_report/wizard/open_items_wizard.py
  account_financial_report/wizard/trial_balance_wizard.py
Labels: approved, bot is merging ⏳, stale

#1350 [IMP] partner_statement: Translate statement title
  partner_statement/report/activity_statement.py
  partner_statement/report/activity_statement_xlsx.py
  partner_statement/report/detailed_activity_statement.py
  partner_statement/report/detailed_activity_statement_xlsx.py
  partner_statement/report/outstanding_statement.py
  partner_statement/report/outstanting_statement_xlsx.py
  partner_statement/report/report_statement_common.py
  partner_statement/views/activity_statement.xml
  partner_statement/views/aging_buckets.xml
  partner_statement/views/detailed_activity_statement.xml
  partner_statement/views/outstanding_statement.xml
Labels: approved, bot is merging ⏳

#1352 [IMP] partner_statement: Translate statement title
  partner_statement/report/activity_statement.py
  partner_statement/report/activity_statement_xlsx.py
  partner_statement/report/detailed_activity_statement.py
  partner_statement/report/detailed_activity_statement_xlsx.py
  partner_statement/report/outstanding_statement.py
  partner_statement/report/outstanting_statement_xlsx.py
  partner_statement/report/report_statement_common.py
  partner_statement/views/activity_statement.xml
  partner_statement/views/aging_buckets.xml
  partner_statement/views/detailed_activity_statement.xml
  partner_statement/views/outstanding_statement.xml
Labels: bot is merging ⏳

#1331 [REF] partner_statement: Allow to override XLSX structure
  partner_statement/report/outstanting_statement_xlsx.py
Labels: bot is merging ⏳

#1360 [15.0][IMP] partner_statement: Translate statement title
  partner_statement/report/activity_statement.py
  partner_statement/report/activity_statement_xlsx.py
  partner_statement/report/detailed_activity_statement.py
  partner_statement/report/detailed_activity_statement_xlsx.py
  partner_statement/report/outstanding_statement.py
  partner_statement/report/outstanting_statement_xlsx.py
  partner_statement/report/report_statement_common.py
  partner_statement/views/activity_statement.xml
  partner_statement/views/aging_buckets.xml
  partner_statement/views/detailed_activity_statement.xml
  partner_statement/views/outstanding_statement.xml
Labels: bot is merging ⏳

#1364 [18.0][MIG] partner_statement (final PR)
  partner_statement/README.rst
  partner_statement/__init__.py
  partner_statement/__manifest__.py
  partner_statement/i18n/ca.po
  partner_statement/i18n/de.po
  partner_statement/i18n/es.po
  partner_statement/i18n/es_AR.po
  partner_statement/i18n/fr.po
  partner_statement/i18n/hr_HR.po
  partner_statement/i18n/it.po
  partner_statement/i18n/nl.po
  partner_statement/i18n/nl_NL.po
  partner_statement/i18n/partner_statement.pot
  partner_statement/i18n/pt.po
  partner_statement/i18n/pt_BR.po
  partner_statement/i18n/ro.po
  partner_statement/i18n/sv.po
  partner_statement/models/__init__.py
  partner_statement/models/account_move_line.py
  partner_statement/pyproject.toml
  partner_statement/readme/CONFIGURE.md
  partner_statement/readme/CONTRIBUTORS.md
  partner_statement/readme/DESCRIPTION.md
  partner_statement/readme/HISTORY.md
  partner_statement/readme/ROADMAP.md
  partner_statement/readme/USAGE.md
  partner_statement/report/__init__.py
  partner_statement/report/activity_statement.py
  partner_statement/report/activity_statement_xlsx.py
  partner_statement/report/detailed_activity_statement.py
  partner_statement/report/detailed_activity_statement_xlsx.py
  partner_statement/report/outstanding_statement.py
  partner_statement/report/outstanting_statement_xlsx.py
  partner_statement/report/report_statement_common.py
  partner_statement/security/ir.model.access.csv
  partner_statement/security/statement_security.xml
  partner_statement/static/description/icon.png
  partner_statement/static/description/index.html
  partner_statement/static/src/scss/layout_statement.scss
  partner_statement/tests/__init__.py
  partner_statement/tests/test_activity_statement.py
  partner_statement/tests/test_outstanding_statement.py
  partner_statement/tests/test_res_config_settings.py
  partner_statement/views/activity_statement.xml
  partner_statement/views/aging_buckets.xml
  partner_statement/views/detailed_activity_statement.xml
  partner_statement/views/outstanding_statement.xml
  partner_statement/views/res_config_settings.xml
  partner_statement/wizard/__init__.py
  partner_statement/wizard/activity_statement_wizard.py
  partner_statement/wizard/detailed_activity_statement_wizard.py
  partner_statement/wizard/outstanding_statement_wizard.py
  partner_statement/wizard/res_config_settings.py
  partner_statement/wizard/statement_common.py
  partner_statement/wizard/statement_wizard.xml
Labels: bot is merging ⏳

#1365 [16.0][FIX] account_financial_report: Log warning in General Ledger Report
  account_financial_report/report/general_ledger.py
Labels: approved, bot is merging ⏳

#1368 [17.0] [FIX] account_financial_report: Fix log warning GeneralLedger Report
  account_financial_report/report/general_ledger.py
Labels: bot is merging ⏳

#1355 [IMP] account_financial_report: Aggregate payment term lines
  account_financial_report/report/general_ledger.py
  account_financial_report/tests/test_general_ledger.py
  account_financial_report/wizard/general_ledger_wizard.py
  account_financial_report/wizard/general_ledger_wizard_view.xml
Labels: approved, ready to merge, bot is merging ⏳
