Repository OCA/account-financial-reporting, pull requests merged in 2025-08, with the labels that each got.

#1265 [16.0][IMP] account_financial_report: Set grouped_by as required with non grouped item description. Fixes display of report when no agroupation is wanted
  account_financial_report/report/general_ledger.py
  account_financial_report/wizard/general_ledger_wizard.py
Labels: approved, bot is merging ⏳

#1378 [17.0][FIX] account_financial_report: Remove buggy empty selection value
  account_financial_report/report/general_ledger.py
  account_financial_report/wizard/general_ledger_wizard.py
Labels: bot is merging ⏳

#1379 [18.0][FIX] account_financial_report: Remove buggy empty selection value
  account_financial_report/report/general_ledger.py
  account_financial_report/wizard/general_ledger_wizard.py
Labels: bot is merging ⏳

#1340 [18.0][MIG] mis_template_financial_report: Migration to 18.0
  mis_template_financial_report/README.rst
  mis_template_financial_report/__init__.py
  mis_template_financial_report/__manifest__.py
  mis_template_financial_report/data/mis_report.xml
  mis_template_financial_report/data/mis_report_kpi.xml
  mis_template_financial_report/data/mis_report_style.xml
  mis_template_financial_report/data/mis_report_subreport.xml
  mis_template_financial_report/i18n/es.po
  mis_template_financial_report/i18n/fi.po
  mis_template_financial_report/i18n/fr.po
  mis_template_financial_report/i18n/it.po
  mis_template_financial_report/i18n/mis_template_financial_report.pot
  mis_template_financial_report/i18n/pt.po
  mis_template_financial_report/models/__init__.py
  mis_template_financial_report/models/mis_report_instance.py
  mis_template_financial_report/models/mis_report_kpi.py
  mis_template_financial_report/pyproject.toml
  mis_template_financial_report/readme/CONFIGURE.md
  mis_template_financial_report/readme/CONTRIBUTORS.md
  mis_template_financial_report/readme/DESCRIPTION.md
  mis_template_financial_report/readme/ROADMAP.md
  mis_template_financial_report/readme/USAGE.md
  mis_template_financial_report/readme/newsfragments/.gitkeep
  mis_template_financial_report/static/description/icon.png
  mis_template_financial_report/static/description/index.html
  mis_template_financial_report/static/src/components/mis_report_widget.css
  mis_template_financial_report/static/src/components/mis_report_widget.xml
  mis_template_financial_report/static/src/css/report.css
  mis_template_financial_report/tests/__init__.py
  mis_template_financial_report/tests/test_mis_template_financial_report.py
  mis_template_financial_report/views/mis_report_instance_views.xml
  mis_template_financial_report/views/mis_report_kpi_views.xml
  mis_template_financial_report/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳
